package com.project01

import android.net.Uri
import androidx.media3.common.MediaItem
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player
import androidx.media3.exoplayer.ExoPlayer
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.project01.ui.EndOfVideoTracker
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File
import java.util.concurrent.CopyOnWriteArrayList

/**
 * Pins down what ExoPlayer actually does at the end of a video, on a real device.
 *
 * The whole GM-controlled playlist depends on it: the game master's Play button has to know
 * whether the current video is finished (advance to the next one) or merely paused (resume it).
 * Getting that backwards for non-last videos cost a field test on 2026-08-17 — the players
 * froze on a still frame of the previous video while the game master played on, and the last
 * video never returned to the blue safe-screen.
 *
 * The behaviour is not obvious and is not something to re-derive from documentation, so it is
 * asserted here against the real player. If a media3 upgrade changes it, these tests fail and
 * name the assumption that broke rather than letting it turn into another lost evening.
 *
 * Requires a connected device:
 * `./project_01_android/gradlew -p ./project_01_android connectedDebugAndroidTest`
 *
 * **Careful:** that installs the debug APK, which has been seen to wipe the app's stored files
 * — i.e. a phone's pre-loaded videos. Don't run it against a phone that is carrying a
 * pre-load you need.
 *
 * The clips in `androidTest/assets` are 2-second solid colours generated by
 * `tools/maketestvideo` (see that folder's README to regenerate or add more).
 */
@RunWith(AndroidJUnit4::class)
class ExoPlayerEndOfItemContractTest {

    private data class Event(
        val kind: String,
        val detail: String,
        val index: Int,
        val position: Long,
        val state: Int,
        val playWhenReady: Boolean,
    ) {
        override fun toString() =
            "$kind($detail) [index=$index pos=$position state=${stateName(state)} pwr=$playWhenReady]"
    }

    private val events = CopyOnWriteArrayList<Event>()
    private val errors = CopyOnWriteArrayList<PlaybackException>()

    /** Fed by the real listener, exactly as PlaybackViewDelegate does in production. */
    private val tracker = EndOfVideoTracker()

    private lateinit var player: ExoPlayer

    @Before
    fun setup() {
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        val context = instrumentation.targetContext
        val clips = CLIPS.map { name ->
            val out = File(context.cacheDir, name)
            instrumentation.context.assets.open(name).use { input ->
                out.outputStream().use { input.copyTo(it) }
            }
            out
        }
        onMain {
            player = ExoPlayer.Builder(context).build().apply {
                // Exactly the production setting: the game master paces the playlist, so the
                // player must never roll from one video into the next on its own.
                pauseAtEndOfMediaItems = true
            }
            player.addListener(object : Player.Listener {
                override fun onPlaybackStateChanged(playbackState: Int) {
                    tracker.onPlaybackStateChanged(playbackState)
                    record("onPlaybackStateChanged", stateName(playbackState))
                }

                override fun onPlayWhenReadyChanged(playWhenReady: Boolean, reason: Int) {
                    tracker.onPlayWhenReadyChanged(reason)
                    record("onPlayWhenReadyChanged", "$playWhenReady, ${reasonName(reason)}")
                }

                override fun onMediaItemTransition(mediaItem: MediaItem?, reason: Int) {
                    record("onMediaItemTransition", "reason=$reason")
                }

                override fun onPlayerError(error: PlaybackException) {
                    errors.add(error)
                    record("onPlayerError", error.errorCodeName)
                }
            })
            player.setMediaItems(clips.map { MediaItem.fromUri(Uri.fromFile(it)) })
            player.prepare()
        }
    }

    @After
    fun tearDown() {
        onMain { player.release() }
    }

    @Test
    fun theEndOfANonLastVideoStaysReadyAndOnlyReportsEndOfMediaItem() {
        playFromStartOf(FIRST)
        awaitEndOfMediaItemPause()

        assertEquals("the index must stay on the video that finished", FIRST, indexNow())
        assertNotEquals(
            "STATE_ENDED must NOT be expected for a non-last video$log",
            Player.STATE_ENDED,
            stateNow(),
        )
        assertEquals("state stays READY$log", Player.STATE_READY, stateNow())
    }

    @Test
    fun theEndOfTheLastVideoReachesStateEnded() {
        playFromStartOf(LAST)
        await("STATE_ENDED after the last video") { stateNow() == Player.STATE_ENDED }

        assertEquals(LAST, indexNow())
    }

    @Test
    fun resumingAVideoParkedAtItsEndRollsIntoTheNextOne() {
        // Why the game master looked fine while the players did not: with no seek in between,
        // simply setting playWhenReady = true again moves on to the next video.
        playFromStartOf(FIRST)
        awaitEndOfMediaItemPause()

        onMain { player.playWhenReady = true }
        await("the next video to start") { indexNow() == FIRST + 1 }
    }

    @Test
    fun resumingAfterAnExplicitSeekToTheEndDoesNotAdvance() {
        // Why the players froze: the host's pause command had seeked them to the end position,
        // and from there playWhenReady = true plays out the remainder and parks again on the
        // SAME video — a still frame, with no way forward.
        onMain {
            player.seekTo(FIRST, CLIP_DURATION_MS - 20)
            player.playWhenReady = true
        }
        awaitEndOfMediaItemPause()

        assertEquals(
            "it must not have advanced — this is the frozen-frame case$log",
            FIRST,
            indexNow(),
        )
    }

    @Test
    fun theTrackerReportsTheEndOfANonLastVideoThroughTheCommandedPause() {
        // The regression guard for the fix: real callbacks into the real tracker, then the
        // commanded pause that shows the blue safe-screen, and the answer the game master's
        // Play button reads must still be "this video is finished".
        playFromStartOf(FIRST)
        awaitEndOfMediaItemPause()

        tracker.onIntentApplied(seeked = false, isPlaying = false)

        assertTrue(
            "the Play button would resume the finished video instead of advancing$log",
            tracker.isAtEndOfVideo(stateNow()),
        )
    }

    // --- harness ---

    private fun playFromStartOf(index: Int) = onMain {
        player.seekTo(index, 0)
        player.playWhenReady = true
    }

    private fun awaitEndOfMediaItemPause() = await("the video to finish on its own") {
        events.any {
            it.kind == "onPlayWhenReadyChanged" && it.detail.contains("END_OF_MEDIA_ITEM")
        }
    }

    private fun onMain(block: () -> Unit) =
        InstrumentationRegistry.getInstrumentation().runOnMainSync(block)

    private fun indexNow(): Int = readOnMain { player.currentMediaItemIndex }

    private fun stateNow(): Int = readOnMain { player.playbackState }

    private fun <T> readOnMain(block: () -> T): T {
        var result: T? = null
        onMain { result = block() }
        @Suppress("UNCHECKED_CAST")
        return result as T
    }

    private fun await(what: String, timeoutMs: Long = 20_000, condition: () -> Boolean) {
        val deadline = System.currentTimeMillis() + timeoutMs
        while (System.currentTimeMillis() < deadline) {
            if (errors.isNotEmpty()) {
                throw AssertionError("playback error while waiting for $what: ${errors.first()}$log")
            }
            if (condition()) return
            Thread.sleep(50)
        }
        throw AssertionError("timed out after ${timeoutMs}ms waiting for $what$log")
    }

    /** The full event log, appended to every failure so a red test explains itself. */
    private val log: String
        get() = buildString {
            appendLine()
            appendLine("--- ExoPlayer events ---")
            events.forEach { appendLine("  $it") }
        }

    private fun record(kind: String, detail: String) {
        events.add(
            Event(
                kind = kind,
                detail = detail,
                index = player.currentMediaItemIndex,
                position = player.currentPosition,
                state = player.playbackState,
                playWhenReady = player.playWhenReady,
            )
        )
    }

    private companion object {
        /** 2-second solid-colour clips; see tools/maketestvideo. */
        val CLIPS = listOf("red_2s.mp4", "green_2s.mp4", "yellow_2s.mp4")
        const val CLIP_DURATION_MS = 2_000L
        const val FIRST = 0
        const val LAST = 2

        fun stateName(state: Int) = when (state) {
            Player.STATE_IDLE -> "IDLE"
            Player.STATE_BUFFERING -> "BUFFERING"
            Player.STATE_READY -> "READY"
            Player.STATE_ENDED -> "ENDED"
            else -> "?$state"
        }

        fun reasonName(reason: Int) = when (reason) {
            Player.PLAY_WHEN_READY_CHANGE_REASON_USER_REQUEST -> "USER_REQUEST"
            Player.PLAY_WHEN_READY_CHANGE_REASON_END_OF_MEDIA_ITEM -> "END_OF_MEDIA_ITEM"
            Player.PLAY_WHEN_READY_CHANGE_REASON_AUDIO_FOCUS_LOSS -> "AUDIO_FOCUS_LOSS"
            Player.PLAY_WHEN_READY_CHANGE_REASON_AUDIO_BECOMING_NOISY -> "AUDIO_BECOMING_NOISY"
            Player.PLAY_WHEN_READY_CHANGE_REASON_REMOTE -> "REMOTE"
            Player.PLAY_WHEN_READY_CHANGE_REASON_SUPPRESSED_TOO_LONG -> "SUPPRESSED_TOO_LONG"
            else -> "?$reason"
        }
    }
}
